<?php

namespace transito\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OcorrenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OcorrenciaRepository extends EntityRepository
{
}
