transito\ContentBundle\Entity\subprefeitura:
    type: entity
    table: null
    repositoryClass: transito\ContentBundle\Entity\subprefeituraRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nome:
            type: string
            length: 50
            nullable: false
    lifecycleCallbacks: {  }

